# Generated by Django 4.2.6 on 2023-10-27 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_consultor', models.IntegerField()),
                ('descrip', models.CharField(max_length=120)),
                ('categoria', models.CharField(max_length=100)),
                ('proyecto', models.CharField(max_length=100)),
                ('valor', models.IntegerField()),
                ('estatus', models.IntegerField()),
                ('notas', models.CharField(max_length=150)),
                ('fecha_asignacion', models.DateField()),
                ('fecha_entrega', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='consultor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=4)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
    ]
