# Generated by Django 4.2.6 on 2023-10-27 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='fecha_asignacion',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='fecha_entrega',
        ),
        migrations.RemoveField(
            model_name='consultor',
            name='clave',
        ),
    ]
