# Generated by Django 4.2.6 on 2023-10-27 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_actividad_fecha_asignacion_actividad_fecha_entrega_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_consultor', models.IntegerField()),
                ('descrip', models.CharField(max_length=50)),
                ('valor', models.IntegerField()),
                ('fecha_asignacion', models.DateField()),
            ],
        ),
    ]
