# Generated by Django 4.2.6 on 2023-10-28 14:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_bonus_descrip'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculoTotales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_consultor', models.IntegerField()),
                ('totalValorActs', models.IntegerField()),
                ('totalValorBonus', models.IntegerField()),
                ('fecha_calculo', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
