# Generated by Django 4.2.6 on 2023-10-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_calculototales'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculototales',
            name='totalValor',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='calculototales',
            name='totalValorActs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='calculototales',
            name='totalValorBonus',
            field=models.IntegerField(default=0),
        ),
    ]
