# Generated by Django 4.2.6 on 2023-10-28 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_calculototales_totalvalor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calculototales',
            old_name='totalValor',
            new_name='total_valor',
        ),
        migrations.RenameField(
            model_name='calculototales',
            old_name='totalValorActs',
            new_name='total_valor_acts',
        ),
        migrations.RenameField(
            model_name='calculototales',
            old_name='totalValorBonus',
            new_name='total_valor_bonus',
        ),
    ]
